name: afri_travel
description: "A new Flutter project."

publish_to: 'none' 
debug: false

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0  
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  firebase_storage: ^13.0.0
  
  shared_preferences: ^2.1.1
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  
  
  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/images/
    

  
  uses-material-design: true
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpeg"
 