// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUUDN9vgdgd7Vw3PJFbUx4OlczlNI-cII',
    appId: '1:846319016529:web:0a19b19dbe13d5e7dcb670',
    messagingSenderId: '846319016529',
    projectId: 'tours-6128e',
    authDomain: 'tours-6128e.firebaseapp.com',
    storageBucket: 'tours-6128e.firebasestorage.app',
    measurementId: 'G-7VCJRYZ4Y2',
  );

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0_aumXEIe_HKGsHBPxwUsBa-Dddq3_Wo',
    appId: '1:846319016529:android:19dcc0f11fc232aedcb670',
    messagingSenderId: '846319016529',
    projectId: 'tours-6128e',
    storageBucket: 'tours-6128e.firebasestorage.app',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOluBNc2rodWRIweUW2cy4cuOAO2WQPCI',
    appId: '1:846319016529:ios:1be65b89ba88a8d1dcb670',
    messagingSenderId: '846319016529',
    projectId: 'tours-6128e',
    storageBucket: 'tours-6128e.firebasestorage.app',
    iosBundleId: 'com.example.tours',
  );

  static  FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOluBNc2rodWRIweUW2cy4cuOAO2WQPCI',
    appId: '1:846319016529:ios:1be65b89ba88a8d1dcb670',
    messagingSenderId: '846319016529',
    projectId: 'tours-6128e',
    storageBucket: 'tours-6128e.firebasestorage.app',
    iosBundleId: 'com.example.tours',
  );

  static  FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUUDN9vgdgd7Vw3PJFbUx4OlczlNI-cII',
    appId: '1:846319016529:web:2661269b9da8568ddcb670',
    messagingSenderId: '846319016529',
    projectId: 'tours-6128e',
    authDomain: 'tours-6128e.firebaseapp.com',
    storageBucket: 'tours-6128e.firebasestorage.app',
    measurementId: 'G-BSFXDSWBJP',
  );
}
